### ISSUE TITLE
Restart Method

### ISSUE THREAD

**Issue by DerekPeacock** [JoysgitHub/CosmicRangers#5]
Why do you create a new MyWorld to restart the game.
Why not call a restart() method in the existing MyWorld??

Why is there not method to handle Win Game

**Comment by MohammadQasim03** [comment]
The world could use an actor. Provide this actor with a graphic or image  that says anything like "Click to try again" or "Press Enter to try again, or restart" The game might then be restarted by looking for a mouse click on this object or by seeing whether enter is pressed.  my new World wouldn't be suitable for restart  because it would be in the world which will automatically make game restart by it self and as a user wouldn't have the control, however, if we do add a method for restart we could insert buttons and other features to make it more controllable for user to implement the feature of restart whenever they wants, however, we could add restart method into win world as well to give the user a chance to try again or to main for better scores this would be great.
